In [183]:
# import packages
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
pd.options.display.max_rows

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import KFold, cross_val_score

In [184]:
diamonds = sns.load_dataset('diamonds')
diamonds.head()

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75


In [185]:
X = diamonds[['carat', 'depth', 'table', 'x', 'y', 'z']]
y = diamonds['price']

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.3, 
                                                    random_state = 2021
                                                   )

model = LinearRegression()
model = model.fit(X_train, y_train)

y_predicted = model.predict(X_test)

print('Train r2 =', model.score(X_train, y_train))
print('Test r2 =', model.score(X_test, y_test))

print('MAE =', mean_absolute_error(y_test, y_predicted))
print('RMSE =', mean_squared_error(y_test, y_predicted))

Train r2 = 0.8583088141424131
Test r2 = 0.8606236418703777
MAE = 878.665345693172
RMSE = 2170006.4781936146


In [186]:
def cross_val_results(X, y, model = LinearRegression(), cv=5, scoring = 'r2'):
    kf = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(model, X, y, cv=kf, scoring='r2')
    print(f"Scores: {scores}")
    print(f"Mean: {scores.mean()}")
    print(f"Std: {scores.std()}")
    return scores


In [187]:
cross_val_results(X, y, model)

Scores: [0.85810488 0.85990252 0.86106744 0.85929087 0.85445913 0.84970439
 0.85640823 0.86147999 0.86109155 0.86470322]
Mean: 0.8586212229892715
Std: 0.004016674694967149


array([0.85810488, 0.85990252, 0.86106744, 0.85929087, 0.85445913,
       0.84970439, 0.85640823, 0.86147999, 0.86109155, 0.86470322])

### Select the features with Ridge, Lasso and ElasticNet models

#### Regularisators

Linear Regression is the most basic method from the regression family, where the model is not penalised for its choice of weights at all. However, this means that during the training process, if the model considers a particular feature important, it will assign a large weight to that feature. This can sometimes cause overfitting in smaller datasets.

Lasso, Ridge, and ElasticNet are methods from the linear regression family that penalize the model for its weights. They reduce model complexity and prevent over-fitting.

#### Ridge

In Ridge regression, the cost function is altered by adding a penalty equivalent to the square of the magnitude of the coefficients.

The penalty term lambda('alpha’ = 1.0(default) in Scikit Learn) regularises the coefficients such that if the coefficients take large values, the optimisation function is penalised.

The higher the alpha is, the bigger the penalty term, and therefore, the magnitude of the coefficients is reduced.

Therefore, Ridge regression shrinks the coefficients, which helps reduce model complexity and mitigate multicollinearity.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html

In [188]:
from sklearn.linear_model import Ridge

In [189]:
X = diamonds[['carat', 'depth', 'table', 'x', 'y', 'z']]
y = diamonds['price']

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.3, 
                                                    random_state = 2021
                                                   )

In [190]:
# in scikit-learn lambda is specified as alpha, and by default it is eqaul to 1. 
# Larger values specify stronger regularization.

ridge_regr_model = Ridge(alpha=1)

ridge_regr_model.fit(X_train, y_train)

,"alpha alpha: {float, ndarray of shape (n_targets,)}, default=1.0Constant that multiplies the L2 term, controlling regularizationstrength. `alpha` must be a non-negative float i.e. in `[0, inf)`.When `alpha = 0`, the objective is equivalent to ordinary leastsquares, solved by the :class:`LinearRegression` object. For numericalreasons, using `alpha = 0` with the `Ridge` object is not advised.Instead, you should use the :class:`LinearRegression` object.If an array is passed, penalties are assumed to be specific to thetargets. Hence they must correspond in number.",1
,"fit_intercept fit_intercept: bool, default=TrueWhether to fit the intercept for this model. If setto false, no intercept will be used in calculations(i.e. ``X`` and ``y`` are expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"max_iter max_iter: int, default=NoneMaximum number of iterations for conjugate gradient solver.For 'sparse_cg' and 'lsqr' solvers, the default value is determinedby scipy.sparse.linalg. For 'sag' solver, the default value is 1000.For 'lbfgs' solver, the default value is 15000.",None
,"tol tol: float, default=1e-4The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for each solver:- 'svd': `tol` has no impact.- 'cholesky': `tol` has no impact.- 'sparse_cg': norm of residuals smaller than `tol`.- 'lsqr': `tol` is set as atol and btol of scipy.sparse.linalg.lsqr, which control the norm of the residual vector in terms of the norms of matrix and coefficients.- 'sag' and 'saga': relative change of coef smaller than `tol`.- 'lbfgs': maximum of the absolute (projected) gradient=max|residuals| smaller than `tol`... versionchanged:: 1.2 Default value changed from 1e-3 to 1e-4 for consistency with other linear models.",0.0001
,"solver solver: {'auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga', 'lbfgs'}, default='auto'Solver to use in the computational routines:- 'auto' chooses the solver automatically based on the type of data.- 'svd' uses a Singular Value Decomposition of X to compute the Ridge coefficients. It is the most stable solver, in particular more stable for singular matrices than 'cholesky' at the cost of being slower.- 'cholesky' uses the standard :func:`scipy.linalg.solve` function to obtain a closed-form solution.- 'sparse_cg' uses the conjugate gradient solver as found in :func:`scipy.sparse.linalg.cg`. As an iterative algorithm, this solver is more appropriate than 'cholesky' for large-scale data (possibility to set `tol` and `max_iter`).- 'lsqr' uses the dedicated regularized least-squares routine :func:`scipy.sparse.linalg.lsqr`. It is the fastest and uses an iterative procedure.- 'sag' uses a Stochastic Average Gradient descent, and 'saga' uses its improved, unbiased version named SAGA. Both methods also use an iterative procedure, and are often faster than other solvers when both n_samples and n_features are large. Note that 'sag' and 'saga' fast convergence is only guaranteed on features with approximately the same scale. You can preprocess the data with a scaler from :mod:`sklearn.preprocessing`.- 'lbfgs' uses L-BFGS-B algorithm implemented in :func:`scipy.optimize.minimize`. It can be used only when `positive` is True.All solvers except 'svd' support both dense and sparse data. However, only'lsqr', 'sag', 'sparse_cg', and 'lbfgs' support sparse input when`fit_intercept` is True... versionadded:: 0.17 Stochastic Average Gradient descent solver... versionadded:: 0.19 SAGA solver.",'auto'
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive.Only 'lbfgs' solver is supported in this case.",False
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag' or 'saga' to shuffle the data.See :term:`Glossary ` for details... versionadded:: 0.17 `random_state` to support Stochastic Average Gradient.",None


In [191]:
ridge_regr_model.coef_

array([10528.20743788,  -213.81483446,  -105.14815225, -1476.08751198,
         279.9279325 ,    75.88011444])

In [192]:
ridge_regr_model.score(X_train, y_train)

0.8583083147536604

In [193]:
ridge_regr_model.score(X_test, y_test)

0.860617136251749

In [194]:
cross_val_results(X, y, model=Ridge(alpha=1))

Scores: [0.85810432 0.85990083 0.86104699 0.85928505 0.8544549  0.84975996
 0.85644554 0.86146543 0.86109999 0.86469047]
Mean: 0.8586253478406893
Std: 0.0039989111511481825


array([0.85810432, 0.85990083, 0.86104699, 0.85928505, 0.8544549 ,
       0.84975996, 0.85644554, 0.86146543, 0.86109999, 0.86469047])

#### Lasso

Lasso is a modified linear regression method where the model is penalised for the sum of the absolute values of the weights. The absolute value of weight tends to be reduced. Some of them may be reduced to zeros. So, the only difference between Ridge and Lasso is that instead of taking the square of the coefficients, magnitudes are taken into account.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html

In [195]:
from sklearn.linear_model import Lasso

In [196]:
lasso_regr_model = Lasso(alpha=1)

lasso_regr_model.fit(X_train, y_train)

,"alpha alpha: float, default=1.0Constant that multiplies the L1 term, controlling regularizationstrength. `alpha` must be a non-negative float i.e. in `[0, inf)`.When `alpha = 0`, the objective is equivalent to ordinary leastsquares, solved by the :class:`LinearRegression` object. For numericalreasons, using `alpha = 0` with the `Lasso` object is not advised.Instead, you should use the :class:`LinearRegression` object.",1
,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"precompute precompute: bool or array-like of shape (n_features, n_features), default=FalseWhether to use a precomputed Gram matrix to speed upcalculations. The Gram matrix can also be passed as argument.For sparse input this option is always ``False`` to preserve sparsity.",False
,"copy_X copy_X: bool, default=TrueIf ``True``, X will be copied; else, it may be overwritten.",True
,"max_iter max_iter: int, default=1000The maximum number of iterations.",1000
,"tol tol: float, default=1e-4The tolerance for the optimization: if the updates are smaller or equal to``tol``, the optimization code checks the dual gap for optimality and continuesuntil it is smaller or equal to ``tol``, see Notes below.",0.0001
,"warm_start warm_start: bool, default=FalseWhen set to ``True``, reuse the solution of the previous call to fit asinitialization, otherwise, just erase the previous solution.See :term:`the Glossary `.",False
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive.",False
,"random_state random_state: int, RandomState instance, default=NoneThe seed of the pseudo random number generator that selects a randomfeature to update. Used when ``selection`` == 'random'.Pass an int for reproducible output across multiple function calls.See :term:`Glossary `.",None
,"selection selection: {'cyclic', 'random'}, default='cyclic'If set to 'random', a random coefficient is updated every iterationrather than looping over features sequentially by default. This(setting to 'random') often leads to significantly faster convergenceespecially when tol is higher than 1e-4.",'cyclic'


In [197]:
lasso_regr_model.coef_

array([10428.72459713,  -207.17710929,  -105.10116029, -1314.75039422,
         206.1914325 ,    -0.        ])

In [198]:
lasso_regr_model.score(X_train, y_train)

0.8582845806625883

In [199]:
lasso_regr_model.score(X_test, y_test)

0.8609772367796547

In [200]:
cross_val_results(X, y, model=Lasso(alpha=1))

Scores: [0.85807164 0.85985284 0.86091432 0.85922435 0.85438366 0.85022092
 0.85852466 0.86135872 0.86115086 0.86458975]
Mean: 0.8588291718066368
Std: 0.0038086251145012617


array([0.85807164, 0.85985284, 0.86091432, 0.85922435, 0.85438366,
       0.85022092, 0.85852466, 0.86135872, 0.86115086, 0.86458975])

#### ElasticNet

ElasticNet is a hybrid of Lasso and Ridge, where both absolute value penalisation and squared penalisation are included, regulated by the L1_ratio coefficient. The L1_ratio takes values between 0 and 1. 

* L1_ratio = 0 is the Lasso penalty.
* L1_ratio = 1 is the Ridge penalty. 

L1_ratio between 0 and 1 is a combination of the Ridge and Lasso penalty. 

For Alpha = 0, it is equivalent to Linear Regression.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html

In [201]:
from sklearn.linear_model import ElasticNet

In [202]:
elastic_regr_model = ElasticNet(alpha=1, l1_ratio = 0.5)

elastic_regr_model.fit(X_train, y_train)

# alpha - penalty term

,"alpha alpha: float, default=1.0Constant that multiplies the penalty terms. Defaults to 1.0.See the notes for the exact mathematical meaning of thisparameter. ``alpha = 0`` is equivalent to an ordinary least square,solved by the :class:`LinearRegression` object. For numericalreasons, using ``alpha = 0`` with the ``Lasso`` object is not advised.Given this, you should use the :class:`LinearRegression` object.",1
,"l1_ratio l1_ratio: float, default=0.5The ElasticNet mixing parameter, with ``0 <= l1_ratio <= 1``. For``l1_ratio = 0`` the penalty is an L2 penalty. ``For l1_ratio = 1`` itis an L1 penalty. For ``0 < l1_ratio < 1``, the penalty is acombination of L1 and L2.",0.5
,"fit_intercept fit_intercept: bool, default=TrueWhether the intercept should be estimated or not. If ``False``, thedata is assumed to be already centered.",True
,"precompute precompute: bool or array-like of shape (n_features, n_features), default=FalseWhether to use a precomputed Gram matrix to speed upcalculations. The Gram matrix can also be passed as argument.For sparse input this option is always ``False`` to preserve sparsity.Check :ref:`an example on how to use a precomputed Gram Matrix in ElasticNet`for details.",False
,"max_iter max_iter: int, default=1000The maximum number of iterations.",1000
,"copy_X copy_X: bool, default=TrueIf ``True``, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-4The tolerance for the optimization: if the updates are smaller or equal to``tol``, the optimization code checks the dual gap for optimality and continuesuntil it is smaller or equal to ``tol``, see Notes below.",0.0001
,"warm_start warm_start: bool, default=FalseWhen set to ``True``, reuse the solution of the previous call to fit asinitialization, otherwise, just erase the previous solution.See :term:`the Glossary `.",False
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive.",False
,"random_state random_state: int, RandomState instance, default=NoneThe seed of the pseudo random number generator that selects a randomfeature to update. Used when ``selection`` == 'random'.Pass an int for reproducible output across multiple function calls.See :term:`Glossary `.",None
,"selection selection: {'cyclic', 'random'}, default='cyclic'If set to 'random', a random coefficient is updated every iterationrather than looping over features sequentially by default. This(setting to 'random') often leads to significantly faster convergenceespecially when tol is higher than 1e-4.",'cyclic'


In [203]:
elastic_regr_model.coef_

array([ 650.97349784,  -36.17013284,  -33.16823051, 1060.04663706,
       1029.06422904,  641.02159189])

In [204]:
elastic_regr_model.score(X_train, y_train)

0.7764777858438835

In [205]:
elastic_regr_model.score(X_test, y_test)

0.7732086661426141

In [206]:
cross_val_results(X, y, model=ElasticNet(alpha=1, l1_ratio = 0.5))

Scores: [0.78351666 0.77830612 0.76570412 0.77730295 0.77729043 0.77355286
 0.73576616 0.7789764  0.78708257 0.78250002]
Mean: 0.773999829839718
Std: 0.013891948134197932


array([0.78351666, 0.77830612, 0.76570412, 0.77730295, 0.77729043,
       0.77355286, 0.73576616, 0.7789764 , 0.78708257, 0.78250002])

The regularisation helps us reduce multicollinearity by decreasing the magnitude of the coefficients. This way, the coefficients that harm the model will have a reduced influence on the target.

The benefit of regularisation over the VIF is that it automatically determines which coefficients harm the model and penalises them, but does not remove them all from the model. Thus, the score will not be significantly affected.

#### Task 1: Train a linear regression model using the Ridge, Lasso, and ElasticNet models.

Validate the created models and explain the results.

In [207]:
# Load the cars dataset
cars = sns.load_dataset('mpg')

# Check dataset
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino


In [208]:
# Review and clean the dataset
cars.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    str    
 8   name          398 non-null    str    
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB


In [209]:
# Drop rows with missing values
cars = cars.dropna()
cars.info()

<class 'pandas.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    int64  
 5   acceleration  392 non-null    float64
 6   model_year    392 non-null    int64  
 7   origin        392 non-null    str    
 8   name          392 non-null    str    
dtypes: float64(4), int64(3), str(2)
memory usage: 30.6 KB


In [210]:
# Define features and target variable
cars_X = cars[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year']]
cars_y = cars['mpg']

# Train-test split
cars_X_train, cars_X_test, cars_y_train, cars_y_test = train_test_split(cars_X, cars_y, test_size=0.2, random_state=42)


**Linear Regression**

In [211]:
# Linear regression model
cars_model = LinearRegression()
cars_model.fit(cars_X_train, cars_y_train)

# Predict on the test set
cars_y_pred = cars_model.predict(cars_X_test)

# Store metrics
linear_r2_train = cars_model.score(cars_X_train, cars_y_train)
linear_r2_test = cars_model.score(cars_X_test, cars_y_test)
linear_mae = mean_absolute_error(cars_y_test, cars_y_pred)
linear_rmse = root_mean_squared_error(cars_y_test, cars_y_pred)

# Display results
print(f"Train R^2: {linear_r2_train}")
print(f"Test R^2: {linear_r2_test}")
print(f"MAE = {linear_mae}")
print(f"RMSE = {linear_rmse}\n")
print(f"Coefficients: {cars_model.coef_}")

linear_cv_scores = cross_val_results(cars_X, cars_y, model=LinearRegression())


Train R^2: 0.8107227953093896
Test R^2: 0.7942349075428587
MAE = 2.5038600897761274
RMSE = 3.2407360783342596

Coefficients: [-0.116173    0.00101347 -0.00227634 -0.00656101  0.06173551  0.76063644]
Scores: [0.8468912  0.71756673 0.84655687 0.76832679 0.78784604 0.75049785
 0.76867992 0.86144984 0.80380594 0.84331323]
Mean: 0.799493441241163
Std: 0.046268703327659526


**Ridge Regression**    

In [212]:
# Ridge regression model
ridge_cars_model = Ridge(alpha=1)
ridge_cars_model.fit(cars_X_train, cars_y_train)

# Predict on the test set
ridge_cars_y_pred = ridge_cars_model.predict(cars_X_test)

# Store metrics
ridge_r2_train = ridge_cars_model.score(cars_X_train, cars_y_train)
ridge_r2_test = ridge_cars_model.score(cars_X_test, cars_y_test)
ridge_mae = mean_absolute_error(cars_y_test, ridge_cars_y_pred)
ridge_rmse = root_mean_squared_error(cars_y_test, ridge_cars_y_pred)

# Display results
print(f"Train R^2: {ridge_r2_train}")
print(f"Test R^2: {ridge_r2_test}")
print(f"MAE = {ridge_mae}")
print(f"RMSE = {ridge_rmse}\n")
print(f"Coefficients: {ridge_cars_model.coef_}")

ridge_cv_scores = cross_val_results(cars_X, cars_y, model=Ridge(alpha=1))


Train R^2: 0.8107227779095144
Test R^2: 0.7942196063542841
MAE = 2.5039229269240204
RMSE = 3.2408565705699526

Coefficients: [-0.11480082  0.00098959 -0.00229315 -0.00656056  0.0616396   0.76039943]
Scores: [0.84686811 0.71754286 0.84655215 0.76833631 0.78783018 0.7504861
 0.76872533 0.86146992 0.80383095 0.84337009]
Mean: 0.7995012017243968
Std: 0.04627637706876955


**Lasso Regression**

In [213]:
# Lasso regression model
lasso_cars_model = Lasso(alpha=1)
lasso_cars_model.fit(cars_X_train, cars_y_train)

# Predict on the test set
lasso_cars_y_pred = lasso_cars_model.predict(cars_X_test)

# Store metrics
lasso_r2_train = lasso_cars_model.score(cars_X_train, cars_y_train)
lasso_r2_test = lasso_cars_model.score(cars_X_test, cars_y_test)
lasso_mae = mean_absolute_error(cars_y_test, lasso_cars_y_pred)
lasso_rmse = root_mean_squared_error(cars_y_test, lasso_cars_y_pred)

# Display results
print(f"Train R^2: {lasso_r2_train}")
print(f"Test R^2: {lasso_r2_test}")
print(f"MAE = {lasso_mae}")
print(f"RMSE = {lasso_rmse}\n")
print(f"Coefficients: {lasso_cars_model.coef_}")

lasso_cv_scores = cross_val_results(cars_X, cars_y, model=Lasso(alpha=1))


Train R^2: 0.8090790405919772
Test R^2: 0.7911638939013964
MAE = 2.531887568957475
RMSE = 3.264830264625581

Coefficients: [ 0.         -0.0022941  -0.00932092 -0.00633103  0.          0.66665168]
Scores: [0.84052381 0.71677857 0.83860823 0.77024061 0.78147316 0.74852024
 0.76892221 0.87212673 0.81762744 0.84410503]
Mean: 0.7998926032995729
Std: 0.04728802185205755


**Elastic Net**

In [214]:
# ElasticNet regression model
elastic_cars_model = ElasticNet(alpha=1, l1_ratio=0.5)
elastic_cars_model.fit(cars_X_train, cars_y_train)

# Predict on the test set
elastic_cars_y_pred = elastic_cars_model.predict(cars_X_test)

# Store metrics
elastic_r2_train = elastic_cars_model.score(cars_X_train, cars_y_train)
elastic_r2_test = elastic_cars_model.score(cars_X_test, cars_y_test)
elastic_mae = mean_absolute_error(cars_y_test, elastic_cars_y_pred)
elastic_rmse = root_mean_squared_error(cars_y_test, elastic_cars_y_pred)

# Display results
print(f"Train R^2: {elastic_r2_train}")
print(f"Test R^2: {elastic_r2_test}")
print(f"MAE = {elastic_mae}")
print(f"RMSE = {elastic_rmse}\n")
print(f"Coefficients: {elastic_cars_model.coef_}")

elastic_cv_scores = cross_val_results(cars_X, cars_y, model=ElasticNet(alpha=1, l1_ratio=0.5))


Train R^2: 0.8094645348684931
Test R^2: 0.7912296416323451
MAE = 2.5291838269762335
RMSE = 3.2643162920098323

Coefficients: [ 0.         -0.00213566 -0.00996605 -0.00630651  0.          0.6794936 ]
Scores: [0.84129694 0.7156629  0.83982414 0.77082715 0.78253138 0.74859599
 0.77010264 0.87002503 0.81736024 0.84452762]
Mean: 0.8000754044683808
Std: 0.047206049790440054


**Compare Results for Linear, Ridge, Lasso and Elastic**

In [215]:
# Performance comparison across all measures used
models = ['Linear Regression', 'Ridge Regression', 'Lasso Regression', 'ElasticNet Regression']

cv_scores = [linear_cv_scores, ridge_cv_scores, lasso_cv_scores, elastic_cv_scores]

performance_df = pd.DataFrame({
    'Model':    models,
    'R2 Train': [linear_r2_train, ridge_r2_train, lasso_r2_train, elastic_r2_train],
    'R2 Test':  [linear_r2_test,  ridge_r2_test,  lasso_r2_test,  elastic_r2_test],
    'MAE':      [linear_mae,      ridge_mae,      lasso_mae,      elastic_mae],
    'RMSE':     [linear_rmse,     ridge_rmse,     lasso_rmse,     elastic_rmse],
    'CV Mean':  [s.mean() for s in cv_scores],
    'CV Std':   [s.std()  for s in cv_scores],
})
print(performance_df)


                   Model  R2 Train   R2 Test       MAE      RMSE   CV Mean  \
0      Linear Regression  0.810723  0.794235  2.503860  3.240736  0.799493   
1       Ridge Regression  0.810723  0.794220  2.503923  3.240857  0.799501   
2       Lasso Regression  0.809079  0.791164  2.531888  3.264830  0.799893   
3  ElasticNet Regression  0.809465  0.791230  2.529184  3.264316  0.800075   

     CV Std  
0  0.046269  
1  0.046276  
2  0.047288  
3  0.047206  


**Results:**
All four models performed very similarly, with only small differences between them. Linear and Ridge Regression gave almost the same results, which suggests that Ridge's alpha=1 penalty isn't strong enough to have much effect — likely because multicollinearity isn't causing a big problem in this dataset.

Lasso and ElasticNet scored slightly lower R² and higher MAE/RMSE on unseen data. This makes sense as both models reduce or remove coefficients, which can hurt performance when the data doesn't have strong multicollinearity to correct for. That said, their CV Mean was very slightly higher (0.800 vs 0.799), so the difference is too small to matter.

Overall, regularisation doesn't appear to be necessary here — Linear Regression holds up just as well without it.


In [219]:
# RIdge regression with different alpha values
alpha_values = [0.01, 0.1, 1, 10, 100]
ridge_cv_results = []
for alpha in alpha_values:
    print(f"Ridge Regression with alpha = {alpha}")
    scores = cross_val_results(cars_X, cars_y, model=Ridge(alpha=alpha))
    ridge_cv_results.append(scores)
    print("\n")


Ridge Regression with alpha = 0.01
Scores: [0.84689097 0.71756649 0.84655683 0.76832688 0.78784588 0.75049773
 0.76868038 0.86145004 0.80380619 0.8433138 ]
Mean: 0.7994935201054437
Std: 0.046268780973267636


Ridge Regression with alpha = 0.1
Scores: [0.84688888 0.71756432 0.84655642 0.76832776 0.78784445 0.75049667
 0.76868452 0.86145185 0.80380844 0.84331898]
Mean: 0.7994942287245641
Std: 0.04626947895112998


Ridge Regression with alpha = 1
Scores: [0.84686811 0.71754286 0.84655215 0.76833631 0.78783018 0.7504861
 0.76872533 0.86146992 0.80383095 0.84337009]
Mean: 0.7995012017243968
Std: 0.04627637706876955


Ridge Regression with alpha = 10
Scores: [0.84667466 0.71735203 0.84649206 0.76840185 0.7876949  0.75039099
 0.76908255 0.861644   0.80405988 0.84381717]
Mean: 0.7995610091674173
Std: 0.04633789803802227


Ridge Regression with alpha = 100
Scores: [0.84545539 0.71664449 0.84519039 0.76813741 0.78676096 0.74997972
 0.77037354 0.86308699 0.8065467  0.84524422]
Mean: 0.79974198064

In [218]:
# Lasso regression with different alpha values
lasso_cv_results = []
for alpha in alpha_values:
    print(f"Lasso Regression with alpha = {alpha}")
    scores = cross_val_results(cars_X, cars_y, model=Lasso(alpha=alpha))
    lasso_cv_results.append(scores)
    print("\n")

Lasso Regression with alpha = 0.01
Scores: [0.84653026 0.71706608 0.84663631 0.76863465 0.78751734 0.75021889
 0.76900805 0.86165612 0.80402932 0.84385032]
Mean: 0.7995147332727737
Std: 0.046405295446621836


Lasso Regression with alpha = 0.1
Scores: [0.84418004 0.71395743 0.84666524 0.77083521 0.78458096 0.74841455
 0.77154813 0.86308675 0.80572279 0.8481576 ]
Mean: 0.7997148690371081
Std: 0.047352691372230034


Lasso Regression with alpha = 1
Scores: [0.84052381 0.71677857 0.83860823 0.77024061 0.78147316 0.74852024
 0.76892221 0.87212673 0.81762744 0.84410503]
Mean: 0.7998926032995729
Std: 0.04728802185205755


Lasso Regression with alpha = 10
Scores: [0.7043033  0.58636694 0.67611858 0.62163736 0.67964212 0.69005164
 0.64798183 0.83236689 0.787819   0.67527866]
Mean: 0.690156631873516
Std: 0.06909176221293231


Lasso Regression with alpha = 100
Scores: [0.70299069 0.59973608 0.68224679 0.6163776  0.67234216 0.67575307
 0.63502064 0.82871898 0.76386401 0.6772878 ]
Mean: 0.6854337816

In [220]:
# ElasticNet regression with different alpha values
elastic_cv_results = []
for alpha in alpha_values:
    print(f"ElasticNet Regression with alpha = {alpha}")
    scores = cross_val_results(cars_X, cars_y, model=ElasticNet(alpha=alpha, l1_ratio=0.5))
    elastic_cv_results.append(scores)
    print("\n")

ElasticNet Regression with alpha = 0.01
Scores: [0.8466739  0.71728184 0.84658736 0.76849611 0.78765628 0.75034069
 0.76890532 0.86158831 0.80396432 0.84367674]
Mean: 0.7995170872561321
Std: 0.04634984380557758


ElasticNet Regression with alpha = 0.1
Scores: [0.84482022 0.71476531 0.84651483 0.76965811 0.78591342 0.74898356
 0.77050385 0.86265064 0.80523127 0.84622573]
Mean: 0.7995266951626709
Std: 0.04702790944729447


ElasticNet Regression with alpha = 1
Scores: [0.84129694 0.7156629  0.83982414 0.77082715 0.78253138 0.74859599
 0.77010264 0.87002503 0.81736024 0.84452762]
Mean: 0.8000754044683808
Std: 0.047206049790440054


ElasticNet Regression with alpha = 10
Scores: [0.76959776 0.6595162  0.7427984  0.68390724 0.73379121 0.72421996
 0.70907578 0.86246421 0.82327637 0.74711563]
Mean: 0.7455762776841488
Std: 0.057813394043529115


ElasticNet Regression with alpha = 100
Scores: [0.70233998 0.59585255 0.68160245 0.61686997 0.67229461 0.67721782
 0.63574086 0.82954512 0.76459988 0.67

In [222]:
# Compare models with different alpha values
alpha_performance_df = pd.DataFrame({
    'Alpha': alpha_values,
    'Ridge CV Mean': [s.mean() for s in ridge_cv_results],
    'Ridge CV Std': [s.std() for s in ridge_cv_results],
    'Lasso CV Mean': [s.mean() for s in lasso_cv_results],
    'Lasso CV Std': [s.std() for s in lasso_cv_results],
    'ElasticNet CV Mean': [s.mean() for s in elastic_cv_results],
    'ElasticNet CV Std': [s.std() for s in elastic_cv_results],
})
print(alpha_performance_df)

    Alpha  Ridge CV Mean  Ridge CV Std  Lasso CV Mean  Lasso CV Std  \
0    0.01       0.799494      0.046269       0.799515      0.046405   
1    0.10       0.799494      0.046269       0.799715      0.047353   
2    1.00       0.799501      0.046276       0.799893      0.047288   
3   10.00       0.799561      0.046338       0.690157      0.069092   
4  100.00       0.799742      0.046579       0.685434      0.064797   

   ElasticNet CV Mean  ElasticNet CV Std  
0            0.799517           0.046350  
1            0.799527           0.047028  
2            0.800075           0.047206  
3            0.745576           0.057813  
4            0.685429           0.065439  


**Conclusion**
Having reviewed the results using Alpha = 1, I re-ran the models across a range of alpha values to see if this would change anything.

Ridge stayed consistent across all alphas, which confirms it isn't sensitive to the penalty strength on this dataset. Lasso and ElasticNet were steady at lower alphas (0.01–1) but dropped off sharply at alpha=10 and above, as the penalty becomes too aggressive and removes coefficients that are actually useful.

Overall this still supports the original conclusion — Linear Regression is the best fit for this dataset, and regularisation doesn't add meaningful benefit. The likely reason is that the dataset does not have severe multicollinearity, so there is nothing for the penalty to correct. The alpha sweep also shows that if Lasso or ElasticNet were to be used, the alpha would need to be kept low (≤1) to avoid hurting performance.